# Generated by Django 3.0.6 on 2020-05-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('course_1', models.CharField(max_length=128)),
                ('course_2', models.CharField(max_length=128)),
            ],
        ),
    ]
